name: Deploy Mqtt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: deploy-production
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            set -e
            cd "${{ secrets.DEPLOY_PATH }}"
            git fetch --prune
            git reset --hard origin/main
            if [ -f .env.production ]; then
              set -a
              . ./.env.production
              set +a
            elif [ -f .env ]; then
              set -a
              . ./.env
              set +a
            else
              echo "[deploy] No environment file (.env or .env.production) found in $PWD" >&2
              exit 1
            fi
            docker-compose down --remove-orphans
            docker-compose build --pull mqtt-service websocket-service
            docker-compose up -d --remove-orphans mqtt-service websocket-service
